name: Backup Firestore

# on:
#   schedule:
#     - cron:  '0 0 * * *'
on: [push]
  
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - name: Create secret files
      run: |
        echo ${{ secrets.GCP_SA_KEY }} | base64 -d > gcp.json
        echo ${{ secrets.FB_SA_KEY }} | base64 -d > fb.json
        
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Backup firestore db in json format
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        npm ci
        npx backfire export gs://nostrdb-backups  --gcpProject nostrdirectory --gcpKeyFile gcp.json --paths twitter --project nostrdirectory --keyFile fb.json