name: Backup Firestore

on:
  schedule:
    - cron:  '0 0 * * *'
# on: [push]
  
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:       
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Backup firestore db in json format
      run: |
        echo ${{ secrets.GCP_SA_KEY }} | base64 -d > gcp.json
        echo ${{ secrets.FB_SA_KEY }} | base64 -d > fb.json
        npm i
        GOOGLE_APPLICATION_CREDENTIALS='gcp.json' npx backfire export gs://nostrdb-backups/ndjson/$(date +'%Y-%m-%dT%H:%M:%S').ndjson --gcpProject nostrdirectory --gcpKeyFile gcp.json --paths twitter --project nostrdirectory --keyFile fb.json